# Exported from https://tiplanet.org/pb/ on Fri Nov 11 04:11:54 2022 (CET)

# ----------------------------
# Program Options
# ----------------------------

NAME         ?= BADAPPLE
ICON         ?= icon.png
DESCRIPTION  ?= "It plays bad apple"
COMPRESSED   ?= YES
ARCHIVED     ?= YES
HAS_PRINTF   := NO

# ----------------------------
# Compile Options
# ----------------------------

CFLAGS   ?= -Oz -W -Wall -Wextra -Wwrite-strings
CXXFLAGS ?= -Oz -W -Wall -Wextra -Wwrite-strings

# ----------------------------

include $(shell cedev-config --makefile)
